export const AGENT = {
  displayName: "Leah Ponticello",
  firstName: "Leah",
  lastName: "Ponticello",
  calendlyLink:
    "https://calendly.com/leah-familyfirstlife/life-insurance-mortgage-protection-options",
  email: "leah.familyfirstlife@gmail.com",
  stateLicense: [
    "Arizona",
    "Alaska",
    "California",
    "Colorado",
    "Florida",
    "Georgia",
    "Hawaii",
    "Illinois",
    "Maryland",
    "Michigan",
    "Mississippi",
    "Montana",
    "Nevada",
    "New Jersey",
    "North Carolina",
    "Oregon",
    "Pennsylvania",
    "South Carolina",
    "Texas",
    "Virginia",
  ],
  nationalProducerNumber: 21005517,
  city: "San Diego",
  state: "California",
  phone: "716-435-0433",
  agencyName: "LP Forward Financial",
  bio: "As a life insurance broker and underwriter, I focus on understanding your family’s unique circumstances and position in order to formulate the best possible options. With a Master’s degree in School Psychology and a history of coaching Division I soccer, working with families has always been at the forefront of my personal and professional values. Families I work with will be heard, understood and respected. As your life insurance broker, I will be advocating on your behalf for a lifetime.",
};
